[target.'cfg(target_os="macos")']
# Postgres symbols won't be available until runtime
rustflags = ["-Clink-arg=-Wl,-undefined,dynamic_lookup"]

[target.'cfg(target_arch = "x86_64")']
rustflags = ["-C", "target-feature=+aes"]