[target.'cfg(target_os="macos")']
# Postgres symbols won't be available until runtime
rustflags = ["-Clink-arg=-Wl,-undefined,dynamic_lookup"]

# Apparently we're not able to use target-feature on macs with ARM, so we shouldn't specify that
[target.'cfg(not(all(target_os = "macos", target_arch = "aarch64")))']
rustflags = ["-C", "target-feature=+aes"]